title: "bestiario 5e"
author: "ankaAR"
description: "Una lista de monstruos de D&D 5e con buscador."
url: "https://ankaar.github.io"
source-url: "https://github.com/ankaar/bestiario5e"
baseurl: "/bestiario5e"
exclude: ['Rakefile', 'README.md']
collections:
  creatures:
    output: true
    permalink: "/creature/:name"
  tags:
    output: true
    permalink: "/tag/:name"
